FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY ./package*.json .
RUN npm ci

# Copy the app
COPY . .

EXPOSE 3333

ENV DATABASE_URL=postgresql://postgres:password@studasso-database:5432/studasso?schema=public

RUN npx prisma generate
RUN npx nx build backend
# TODO: Remove useless file after building

CMD [ "node", "dist/apps/backend/main.js" ]
