FROM node:lts-alpine as build-stage
WORKDIR /app
ENV NODE_ENV=production

# Install dependencies
COPY ./package*.json /app/
COPY ./tools /app/tools
RUN npm ci

# Copy the app
COPY . .

EXPOSE 4200

RUN npx nx build frontend-school
# TODO: Remove useless file after building

FROM nginx

RUN mkdir /app
COPY --from=build-stage /app/dist/apps/frontend/school/ /app
COPY nginx.conf /etc/nginx/nginx.conf
