version: '3'
services:
  # frontend-school:
  #   build: ./apps/frontend/school/
  #   ports:
  #     - '8081:8081'
  frontend-association:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend.association
    ports:
      - '4201:80'
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - '3333:3333'
    environment:
      POSTGRES_DB: studasso
    networks:
      - backend
    depends_on:
      - database
  database:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studasso
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - stud-asso:/db
    networks:
      - backend
    container_name: studasso-database

volumes:
  stud-asso:

networks:
  backend:
