FROM node:lts-alpine as build-stage
WORKDIR /app

# Install dependencies
COPY ./package*.json /app/
COPY ./tools /app/tools
RUN npm ci

# Copy the app
COPY . .

EXPOSE 4202

RUN npx nx build frontend-student
# TODO: Remove useless file after building

FROM nginx

RUN mkdir /app
COPY --from=build-stage /app/dist/apps/frontend/student/ /app
COPY nginx.conf /etc/nginx/nginx.conf
