version: '3'
services:
  frontend-school:
    build: ./apps/frontend/school/
    ports:
      - '8081:8081'
  frontend-association:
    build: ./apps/frontend/association/
    ports:
      - '4201:4201'
  backend:
    build: ./apps/backend/
    ports:
      - '3333:3333'
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: default-password
      POSTGRES_USER: stud-asso
    volumes:
      - stud-asso:/db
    ports:
      - '5432:5432'

volumes:
  stud-asso:
