export const enum ERROR {
  ACCESS_DENIED = 'Access Denied',
  ASSO_NAME_ALREADY_EXISTS = 'Association Name Is Already In Use',
  ASSO_NOT_FOUND = 'Association Not Found',
  BAD_STOCK_ACTION = 'Provided action has to be either: create, update or delete when creating a stock logs',
  CANNOT_DELETE_ROLE = 'Cannot Delete Role',
  CANNOT_UPDATE_ROLE = 'Cannot Update Role',
  EMAIL_ALREADY_USED = 'Email Already Used',
  EVENT_NOT_FOUND = 'Event Not Found',
  INVALID_GOOGLE_TOKEN = 'Invalid Google Token',
  NEWS_NOT_FOUND = 'News Not Found',
  PRESIDENT_NOT_FOUND = 'President Not Found',
  ROLE_NAME_ALREADY_EXISTS = 'Role Name Is Already In Use',
  ROLE_NOT_FOUND = 'Role Not Found',
  STOCK_NOT_FOUND = 'Stock Not Found',
  USER_NOT_FOUND = 'User Not Found',
}
