version: 2.1
orbs:
  nx: nrwl/nx@1.0.0
jobs:
  agent:
    steps:
      - checkout
      - run: npm install
      - run:
          command: npx nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: 'cimg/node:14.17-browsers'
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel --max-parallel=3
      - run: npx nx affected --base=$NX_BASE --target=test --parallel --max-parallel=2
      - run: npx nx-cloud stop-all-agents
  pr:
    docker:
      - image: 'cimg/node:14.17-browsers'
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel --max-parallel=3
      - run: npx nx affected --base=$NX_BASE --target=test --parallel --max-parallel=2
      - run: npx nx-cloud stop-all-agents
workflows:
  build:
    jobs:
      - agent:
          name: 'agent1'
      - agent:
          name: 'agent2'
      - agent:
          name: 'agent3'
      - main:
          filters:
            branches:
              only: main
      - pr:
          filters:
            branches:
              ignore: main
